keys:
  - &users:
      - &gideon CFDDC2FC81DEE54D1C4BFF58538305FABF463DE5
  - &hosts:
      - &poseidon age10exe2vqxqapa87r7xxyrzessgk9efjac05s3znsl66xzfm6pqgpqp6793w
      - &hades age1nkjg6grfv5hjxfpav4k2w3y4t7p7j2gk34huu7cjrkrvrdun05mst0rtal
      - &athena age1yyzawdy20cynpv4pzy3a36lsykxu733e0g4cwvmjnvaup64s8swscxhhst
      - &do-vps-test age1hqmjhpm7a9w2cnjdvnutk65uqkjpd4huyvd5udqs5yxlzuthyupspxq2ft
      - &alpha age1r70gxq3w2e9z26de95zvxmpshxh7k8xppqpl7zhvr506u37m0ffqyp68fq
      - &beta age1qft762fcg4ryt20k87j8fx9fq982p9gfne6vy7q0525xjkdlss2sqwcge8
creation_rules:
  - path_regex: gideon_secrets.yaml$
    key_groups:
      - age:
          - *poseidon
          - *hades
          - *athena
          - *alpha
          - *beta
        pgp:
          - *gideon
  - path_regex: athena_secrets.yaml$
    key_groups:
      - age:
          - *athena
        pgp:
          - *gideon
  - path_regex: vps_secrets.yaml$
    key_groups:
      - age:
          - *do-vps-test
        pgp:
          - *gideon
  - path_regex: .*kubeconfig\.yaml$
    key_groups:
      - age:
          - *alpha
          - *beta
        pgp:
          - *gideon