keys:
  - &users:
      - &gideon CFDDC2FC81DEE54D1C4BFF58538305FABF463DE5
  - &hosts:
      - &poseidon age10exe2vqxqapa87r7xxyrzessgk9efjac05s3znsl66xzfm6pqgpqp6793w
creation_rules:
  - path_regex: gideon_secrets.yaml$
    key_groups:
      - age:
          - *poseidon
        pgp:
          - *gideon
