keys:
  - &users:
    - &gideon age1wrxmxqqq5l25uvrf3hjxya34mxk3xhhn86vuwf7n8mnm7gkajdps0natng
  - &hosts:
    - &hades age1nkjg6grfv5hjxfpav4k2w3y4t7p7j2gk34huu7cjrkrvrdun05mst0rtal
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *gideon
      - *hades
      pgp:
