keys:
  - &users:
    - &gideon CFDDC2FC81DEE54D1C4BFF58538305FABF463DE5
  - &hosts:
    - &hades age1nkjg6grfv5hjxfpav4k2w3y4t7p7j2gk34huu7cjrkrvrdun05mst0rtal
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *hades
      pgp:
      - *gideon
  - path_regex: gideon_secrets.yaml$
    key_groups:
    - age:
      pgp:
      - *gideon
