keys:
  - &users:
      - &gideon CFDDC2FC81DEE54D1C4BFF58538305FABF463DE5
  - &hosts:
      - &poseidon age10exe2vqxqapa87r7xxyrzessgk9efjac05s3znsl66xzfm6pqgpqp6793w
      - &hades age1nkjg6grfv5hjxfpav4k2w3y4t7p7j2gk34huu7cjrkrvrdun05mst0rtal
      - &athena age1yyzawdy20cynpv4pzy3a36lsykxu733e0g4cwvmjnvaup64s8swscxhhst
      - &do-vps-test age1m7p4yrmzp2w4hcwpsc8hg6vxaprrq5mffjs9mv7vxdjqd7628d0qt5ln3k
creation_rules:
  - path_regex: gideon_secrets.yaml$
    key_groups:
      - age:
          - *poseidon
          - *hades
          - *athena
        pgp:
          - *gideon
  - path_regex: athena_secrets.yaml$
    key_groups:
      - age:
          - *athena
        pgp:
          - *gideon
  - path_regex: vps_secrets.yaml$
    key_groups:
      - age:
          - *do-vps-test
        pgp:
          - *gideon
