crowdsec:
    api_key: ENC[AES256_GCM,data:gOfGn7Khcezpk4hW8t8U/MqDXlhPsuE6kb5R4HUqKB6yI9uK8R0yrkmAfw==,iv:RRQYG1mmiGq8typLSycBSbkn0wAXPywAZgY9ho0VwT8=,tag:3r/3NxdD8j22yujpUoSymA==,type:str]
mealie:
    env: ENC[AES256_GCM,data:sJLkFeRAgsbPetKAXQ9oQih+q4HCDem6l8r+QpEziMUcVXjiI6dk0It/6GoO23FpzVoPAmzPNlMXrFENB3uc2pwaCda7snbSZJ7qUmbZCZBGkC2u4CWWg8vlTFp02veJOfT+bo9aGetgl81W7fDyS/PtigySrbm8DspJveG3IsTkWu8/fkhTI8fKhcqWS/pebHmvCjhmtXckjvS01FnjMyt7/XfI2o32NBGOi4YciE4A1uHndZsZJWQI43sPXqjWR1UBTQHpouxR3rWliRFmH7KKD7jsUuXRe/xVI1Z87eGyTKpkmiiXnNABk3zgbIl/,iv:5yfGhe4q9cYG/VgX0qtR1XHP7HAO2Kz37qYwoPIq834=,tag:ew30vp3kOqo8KYdwSddf4w==,type:str]
paperless:
    admin_pass: ENC[AES256_GCM,data:mD0jShz7DRVUJNsWQWI=,iv:EGj5p4ZkvrbWkh3RLN1r5+j+7kHER5bBKJrdek8OHZs=,tag:ps8F1cntaZWRpop5wOsFSg==,type:str]
romm:
    env: ENC[AES256_GCM,data:ouP+wPntksy1TjDpQyLhMJOJc4KGRePlXTC/15ijjJ5g4aCdcsujPqwsgRaN+8vevQIUsusOC9WQbmoe9crN+wbgsdQRck1n+2VpmM7OgMrzgwmORrQm6RbrbsyT//zDdsNeLrqIWkl2PQ6qsowLFHlHA7hNnDLaWscdOjLfYDEQVHDdpcWErPCCthKjzsJAUE1faI/JcSmqxz8Ckm3Ql7aROSQop7/LvI1PsatnU4HB07D9FySPeFlU1KY1DM1WEr+gTpxL2sBg4QFtxL2AFB2ZPmTRcuhXOm840a0ycgwxWomealQtJpc7Dh8VLYXPk0KVGu4VjitLJGg1JNvrkZNlVM6OspejqrFAltfJ/7n4ah1oaraU/AIwEKlwWIizEQW0iIiwSkFdhoPfxPC9KmGj7LLI95wU1t0vK3LUxgQlaHVPRkv2g5b4hDc2JaPi0ZvqpoOYPE+E3Hw4dPuv2qpIWLZsJnlFpAqV2hP2CEirwc23vu6H,iv:J3VzkpCnY9SNRApa+WMZCLPK5j9MkeeCDJs6kngICKE=,tag:pcU6TW8OHxHy2nbvT9HHog==,type:str]
traefik:
    env: ENC[AES256_GCM,data:ST+oR5xoZ9/pi7z6ui/cY2h3IfHvwJuGtqFttLqneQoC/zoEmglf033EUyuMBVG1rKHyUdVdO368LPvEr26ziPNE787ZxVsx7+Mfr83bpyVpnHc3ig4=,iv:bMrQt4PYsjeuLSrun8fygnIwAvT9HJ41wQQMiIYeDx0=,tag:PRzsdck88aMEhd2DgCY1PA==,type:str]
vaultwarden:
    env: ENC[AES256_GCM,data:f56Gm8TNEetrRtyLdOS0lEPHYKKLH1yDXzmFSso5iGvZo+sQJU1+l5rFUb6EqOfIQ9aazQsN/FEBBwOeiwCDzaxmg/28yzaeVy4ErRTS7hNLF4jwVobbN1NIjeuW1RYEDvKAh8YOiotQiDT4YSWTHRMRjYtBmskypuJ+Qguf/VpTaMnWO9hctiqjVoZ7JeY2cROqLoiSzlU1oICCEjm9Pe/5Aub5d+Bq76GFCGdtPrxiU7cXZCW1QPWUVZ2EeFHxURW0SsvEcgO6cALqbhNL2bPQiop1DSvAqkZ1gqfcy/ECr+8BXtYRy0H4ia/hPXZLHz/ffXi2XGoDdwbYKbHketaK68OU,iv:jH5rImoIut84NmlmLkVJm2L0R+ucZrLeLBmebDZdM+w=,tag:dqY4hoCDW0bsNkOAqSDYlw==,type:str]
sops:
    age:
        - recipient: age1yyzawdy20cynpv4pzy3a36lsykxu733e0g4cwvmjnvaup64s8swscxhhst
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXSjltWkt6a090VkFRMG5j
            eVJXMWZkSllaSUsxRUdvMlNMOVZQWGduakg0CjNuUlRRSXdyNWV1ZFNnQTFaZ3lQ
            VlA4YkN6d3dvbFZLa28zZnIyZXBMT1UKLS0tIHp4M1VMTUV0VkZKZytiMjZsNStK
            R0Y4TjJQRXdIRG0wcTBqS3NkbW1UT3MKxbDRwAgvFiuPL/BIzSS8RnY9gCQ+ObfC
            GkAOhXidmAvkE3QB8gepDHciGyEUW4q6VX58ao+6CD48q48IuSia4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-23T23:40:36Z"
    mac: ENC[AES256_GCM,data:8dNPswu8VkwwMbYfQpKwnR9BNZhT1rlaMBXtgr6qBwQRUgfVM6mlw+NG7iTXoNS+xnMTcELo/KxT2jLfOpzjLOSGZsbLKrMHleUjrxTb4wgEkCSWr9BvsXpMIo9QqpUOx6BFGGpH/sAxzFhXmNRAfpACCTze9fAS8XbyBzcrjKE=,iv:ElF+xhVU6n2pxITBVopB4Z6xYT+EDYFIo64ya0U+0QI=,tag:2qNbT9u87ZskwGCeZMbLJQ==,type:str]
    pgp:
        - created_at: "2025-05-24T19:22:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DW7pTteVLMFESAQdA7TeSQ9vGzWlPlZlagZwpLW6RQGy/PfD5eMrURpZssi4w
            qqQ44H5Wf8v9tfFFpWiVX+TpOGq46gFHdoBGzGcoldd7cFNoNXUUyHyB9QFnatjF
            0l4BBWJNbYVagGmCOQO4MgARWcVtu9ig9J+dYnU4ukunafBBCERG6qrmZXAkK4Es
            3cEnv85pQrdUITqlGl6ERBX08c9tsNXvghqYYsrnmGNkTf5gkF17SXwb38DXkzoR
            =ydoW
            -----END PGP MESSAGE-----
          fp: CFDDC2FC81DEE54D1C4BFF58538305FABF463DE5
    unencrypted_suffix: _unencrypted
    version: 3.10.2
