freshrss:
    apikey: ENC[AES256_GCM,data:8f1jQMCfgYZ4yW/qu1I=,iv:bSSYoaljZ/byDTGLusyGYAatd2BT4AKbLeN6Eym6aFI=,tag:MopqKjiZ47tPEPswsMHBOQ==,type:str]
weatherapi:
    apikey.json: ENC[AES256_GCM,data:IxAoeDvSwEWbXT6cpVz0TAd9aV51cA4Om4zWLGabE4IeE4GIV7etENZJeAiUQQ7Xr5LCSTkTAjx5,iv:MiquMnYblV/KULtScXshZrDf27Vv3euNMO0IUToPS9A=,tag:MsQoWjlq8TgXJf444BRVNw==,type:str]
wolfegideongmail:
    client_id: ENC[AES256_GCM,data:8bNijLKJP+2FCIsrlKHl1ckLY8B7giZHtdCnnTwcykwHjQtiXOid45Xi93smiWPReSZfqDQG2tOADcfA1N48HvJRWTf3hjIX,iv:LY18zWLVrHx2zoTv7H4QNeBQr2VuQ3XPRL0MLHpTcr8=,tag:AteziKY6m4XcchmKGbICRQ==,type:str]
    client_secret: ENC[AES256_GCM,data:PyiMEn7bvQCV0PIVdB2BNsBO+bluj4mc6w1v31x4YtbdF1Y=,iv:gabCJQzDayhrNBSULb26GA+SZZbyus51RSnqskcKVzA=,tag:bC0zgB8R2mbWPaWGFmvmzA==,type:str]
    mbsync_password: ENC[AES256_GCM,data:gzew1eQ1AdEaP1VxOnKg3lLdfQ==,iv:PB2ch8pSybpZLFDgdxEKexPqWJJvnJnPb1NkfQnNxkw=,tag:mCyi2UE55G3jyFuMvKYEUA==,type:str]
gideonwolfexyz:
    mbsync_password: ENC[AES256_GCM,data:mSn9L2LvxQUnT411PWg=,iv:a1P2SXvBWhwWTRN4tZMuanaxH+fI0LaJHso+zMhgDDI=,tag:+Hde2AvzaLrGCJ4soYzyhQ==,type:str]
gideonwolfecom:
    mbsync_password: ENC[AES256_GCM,data:ZkrfDSpWOPlLtYdq,iv:uAlbeYGeau1uE97QxvEpS88np9l5suSyy3BCOVYvifc=,tag:UK4YUmQBKEmJPbE+ZkzPzw==,type:str]
irc:
    libera:
        nick: ENC[AES256_GCM,data:nsPC9rv4L1Vl,iv:M4GrQs4k5wSKLwzX8RH/L6elKOyzcHpjdZRNAwOw5ps=,tag:hdu55i5IX2PU+t9tRcLiUw==,type:str]
        password: ENC[AES256_GCM,data:F9YbSMWrNGy/Y058vds=,iv:qxupWXOIfj9amybBfkx6Zo3mQYqvReYNk/8DOAtiC4Q=,tag:WKAgmANnOEBv3RnPxYOH5A==,type:str]
    weechat:
        sec.conf: ENC[AES256_GCM,data:2Wx3sMGBa/ZBqYPaeKzoGQcPbuuRASVwBgY4pd2XD61cswdDFFgifFOkxixsuvfhpjlUvyYHoBob00QfKZ/KwmTudAfoBvNUFyKTSv6QU+l7nTllkUFbmHLLCV+IaTgo3xbHmqvtZNjGwbWpKi7el4/89Dn1toF1tnmnIk+n3ZAF+Ch8,iv:gcjE7OkFT2LsC46LVzS8kWoVwJyVh4K1VZJ/26HKzIw=,tag:F8K1tKOFkn49jqlSjm4O6A==,type:str]
termsonic:
    termsonic.toml: ENC[AES256_GCM,data:hePpk2l/LB64f1OHQY9fsg0nXmgDcIB3FF52t+bZPmLQQI6QM6ShxLKhEVir5IqytwGfh9r5jYFVvrMKHXRUYLrzNgbTPccgtXf3Cnu0sra4GtdzNX/Icw==,iv:u3P1cv4huxTffbxwztFAMAQiLc+Y0AtBU0i4iyihqvw=,tag:9yjCp3WT1d9UJZI5KoLaqg==,type:str]
ssh:
    gideon_ssh_sk:
        private_key: ENC[AES256_GCM,data:rqCPQfslqkjc1798GTlnGj1qEiCFCgzUBCi5OtW/M6fBNtRAmLzXK+yPIEGxxPo1lTHut57VBaK7u90xNKPstKWlFWjJ8CFcxPOKRUTNelwB3PoAUiWCsx12UdFnNccevTrbg+Vkb5vIsooZUWt7UgeYYFaAISjA6Wgi1IQRgexNcOuD0i50uWVqx4wojWmGpHFY2sXHzeq9lE9Bn6Lv7ZqxvDWyiIZ9lfOZInr4f4IGFdf9mxlMYDQappHU921vgPCcCDA/umKGuPv1Cs+3Z2RX7Mx6pz4xolBOqcKjaXwuO8ywdfYfeT0YzB0ew8uPQM4m6dKnjsB0xsFghXetKtgnRgbGMCMUtL3qPz7L9NybBKsREk4NCAo2/HP7AitXQ4DFbPlFJMtg4MQa2p9hn8SOoK7jX+dWjk+MbTvzirJRkDbBvE0+GUTPaeFph3mByQYdICbjOKef4TjULvvzKj/M5bpba30ms/IlO3tSX/is0Itd1/rIh2Y5KLuHCVSXKvTGFore2A9ITeGBGSVuRspq8F6hS52QE/xdcIKydWHxJj60B3mx5lZHCKixxI1nMCMlGHRbaKGYlugYG6DFHrxE+x6+W/8HAJvVdMi4zT/NqhFShl4GfA==,iv:TR57lGXD6biqXydLQZjd2Wy5cS8os5x6EKxUNZBrcak=,tag:dXvWF9sBqs6H06ae0edEXQ==,type:str]
sops:
    age:
        - recipient: age10exe2vqxqapa87r7xxyrzessgk9efjac05s3znsl66xzfm6pqgpqp6793w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaalczYlhyM0RWNU9oN01J
            c2NkVXBnaEFHUk5YTUV0QURPcHExeVBaRVFFCmhXMWViVVVhYmxMV2xDMnNQeGZl
            dll4MTF6UzFwdmhQN3pFSi8rZlRxUTQKLS0tIFN0dmlIaTRJYUFWK0hZVW1tWkc2
            ZjJhM2tjQ0g4TDg0OTd3NWVBSnhnbnMKxIOkXLOs+lM3YgGIVMsJvYKX6LJ+YSTb
            rDc6Uz/46k9DbKMvm5j/+/op+qpQU9O+IX/d6meASFhPowseTcFKDw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nkjg6grfv5hjxfpav4k2w3y4t7p7j2gk34huu7cjrkrvrdun05mst0rtal
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSK05hZm93N2FlQlBWOFlT
            U0lBd0oyc21EYm95Q3FNLzRqa1Y1Mjlkd0g4CnFRUEhHQnNSaHJyYTRzRzI2M0RP
            Wk10R00vSzIwQWFBdDF2NHRuSHY0dzgKLS0tIDlGdENxMHJoeHBLVlEyMk1ZK0FM
            M0hGYytybVQwRC9IdTNiQ0tOKzdRTFkKmLRD6J5kwtF9GDIKRMgEfW0+bJR8UbJs
            lzBfXxNRmgpXJWXYAkoO9Bs9g89GhMA5PVuXRtT8g+5ME3utNnLuVw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yyzawdy20cynpv4pzy3a36lsykxu733e0g4cwvmjnvaup64s8swscxhhst
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMXl2U2h4UjdrRCtCZVI0
            clNWSXZTSWxMdmh3R2FYZXVXVlVYdzh4K1ZvCkRmN1VzQTJ4bXhlL2RVQmZPbVNL
            U3RHZDNjcXVCMEJBbUZsUWh1anE5dE0KLS0tIEI4Y29LOTc1SXBNcGVaMWE2VWRP
            WW14WnZSWE94cVpSLytYbXFIK0JoTm8KrBv2PRkTFgBf6dIPWj89yQH4Sn0D5hhM
            m2uRZ8qz5u/zU0TcksXJTTA54cTGKmY43Er6zPe5c3q0E68dESPcdw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r70gxq3w2e9z26de95zvxmpshxh7k8xppqpl7zhvr506u37m0ffqyp68fq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3VkJqU0oxbUVEZHZ0elJv
            RUhHZjZpQ0x6QUY5OEpCYW5XbHNRN1A0Um0wCnlFQ0pjUlFWc0N6TFUyanF0RVAr
            RCt2cWFObW5Yc2k5cGplUFg2Y0d6NjQKLS0tIHkyWE96d0R2Sm1vcEdqZGlwaEY1
            ZGhsOUYrS0JaUnFnWGF0M3J2YVB1OEkKmLleCJ907cHrTOighTksagK//8IfQZ0z
            0rrs9K66samtMUYY4YtiDsfaNYIlvskJAgmFHPeCrYgtENrgaJx06w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qft762fcg4ryt20k87j8fx9fq982p9gfne6vy7q0525xjkdlss2sqwcge8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdytMeVUzWDV0alhERnE2
            djN2anFDWnJpdnl5OStjVnk5YTg4ZTZlTjA4CjgxS29YTnVrYnJQSUx0dUg2N1la
            b1UzRjcxQ3o2eG1uVHVDcmxVc0MybU0KLS0tIEt6aisvUDRNQXJMZnluZlpRYWNW
            d2U5ektPSG80VE9IZWlQVlNPZDBlRFkKr2mG59t8PNTSNYPMOdYNNWQgmbX/dsNt
            1sSNDrh3NnOF0oDLoNMCBqx4LMoYqBuh1/R7GCP9vGyGdUcZL0NKLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-26T21:02:38Z"
    mac: ENC[AES256_GCM,data:hY3m1HsNo2iYN/dIhKbW6Bc2jzbFSNfBx7gHxjQG5hNfNJz9k0qbGc9oDRMWZxGtt1jCO5gP3ECEcIxPRicGRMQKOh3nc0dIpuYF05t+TiCj7icQZhHhD7TF5NmHJl7nGf4Li0rUYmW6rpDpgaTadx3nUx9evmtYi26W+wWeEjQ=,iv:fcpz7hIB/kFWdr0SkcxiVRnAGqNqbwJHNc++xtKGbic=,tag:4GQ6tHeEF5/KYyutooAIiA==,type:str]
    pgp:
        - created_at: "2025-10-07T23:21:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DW7pTteVLMFESAQdAPhtZtSXyMwDeV79P6fGAhXGKDWuzpBd3q1Q9kH9yJA0w
            C9OkmCwF+O8glWsqdGji+ytikrtI0AFgYC+OnTu9PJx1HYHb8EJ1a3Fhj4M5ARvG
            0l4BTiB3pKL+JMYuG+BkTxGHLnvOw3/u2ifiS0LXARub9X5w0rp78oLRkOO1425S
            UTs6Udl24LhB9Th01a8sc92TYInXSgLKCd6Fu9C74S1LIkhi9wafeXxUbmwbVSfu
            =n5+G
            -----END PGP MESSAGE-----
          fp: CFDDC2FC81DEE54D1C4BFF58538305FABF463DE5
    unencrypted_suffix: _unencrypted
    version: 3.10.2
