freshrss:
    apikey: ENC[AES256_GCM,data:8f1jQMCfgYZ4yW/qu1I=,iv:bSSYoaljZ/byDTGLusyGYAatd2BT4AKbLeN6Eym6aFI=,tag:MopqKjiZ47tPEPswsMHBOQ==,type:str]
weatherapi:
    apikey.json: ENC[AES256_GCM,data:IxAoeDvSwEWbXT6cpVz0TAd9aV51cA4Om4zWLGabE4IeE4GIV7etENZJeAiUQQ7Xr5LCSTkTAjx5,iv:MiquMnYblV/KULtScXshZrDf27Vv3euNMO0IUToPS9A=,tag:MsQoWjlq8TgXJf444BRVNw==,type:str]
wolfegideongmail:
    client_id: ENC[AES256_GCM,data:8bNijLKJP+2FCIsrlKHl1ckLY8B7giZHtdCnnTwcykwHjQtiXOid45Xi93smiWPReSZfqDQG2tOADcfA1N48HvJRWTf3hjIX,iv:LY18zWLVrHx2zoTv7H4QNeBQr2VuQ3XPRL0MLHpTcr8=,tag:AteziKY6m4XcchmKGbICRQ==,type:str]
    client_secret: ENC[AES256_GCM,data:PyiMEn7bvQCV0PIVdB2BNsBO+bluj4mc6w1v31x4YtbdF1Y=,iv:gabCJQzDayhrNBSULb26GA+SZZbyus51RSnqskcKVzA=,tag:bC0zgB8R2mbWPaWGFmvmzA==,type:str]
    mbsync_password: ENC[AES256_GCM,data:gzew1eQ1AdEaP1VxOnKg3lLdfQ==,iv:PB2ch8pSybpZLFDgdxEKexPqWJJvnJnPb1NkfQnNxkw=,tag:mCyi2UE55G3jyFuMvKYEUA==,type:str]
gideonwolfexyz:
    mbsync_password: ENC[AES256_GCM,data:mSn9L2LvxQUnT411PWg=,iv:a1P2SXvBWhwWTRN4tZMuanaxH+fI0LaJHso+zMhgDDI=,tag:+Hde2AvzaLrGCJ4soYzyhQ==,type:str]
gideonwolfecom:
    mbsync_password: ENC[AES256_GCM,data:ZkrfDSpWOPlLtYdq,iv:uAlbeYGeau1uE97QxvEpS88np9l5suSyy3BCOVYvifc=,tag:UK4YUmQBKEmJPbE+ZkzPzw==,type:str]
irc:
    libera:
        nick: ENC[AES256_GCM,data:nsPC9rv4L1Vl,iv:M4GrQs4k5wSKLwzX8RH/L6elKOyzcHpjdZRNAwOw5ps=,tag:hdu55i5IX2PU+t9tRcLiUw==,type:str]
        password: ENC[AES256_GCM,data:F9YbSMWrNGy/Y058vds=,iv:qxupWXOIfj9amybBfkx6Zo3mQYqvReYNk/8DOAtiC4Q=,tag:WKAgmANnOEBv3RnPxYOH5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nkjg6grfv5hjxfpav4k2w3y4t7p7j2gk34huu7cjrkrvrdun05mst0rtal
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2OUlLeWJEejJwMlJRdGlV
            OEVNUEhOT2NyVlRYL2xieC9kd3JMMy9BNnpzCnRydkgrSjVCcDVqcXFPRkxwQkhV
            T2dhWTZtVHdBaHNzNm9EUEsxbHp6U1EKLS0tIEx5KzMwYnp1NzJLWE1kd1NrdVU5
            alVrcGhMQU95ZU5ZZC9KZHZPbWsyb1UKMViWaqvb54n8AKLza/DDUZNQ8ANuJJHr
            gnQ8TRfqPRVGGx9Vev/ZgTClwFiQtBVmshn48ia6uthbTaf9LFi4/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-14T02:44:54Z"
    mac: ENC[AES256_GCM,data:vxdPo0q0izrVu9u4O3o0/fMNqncx/g6eMpPXWbi+vDNOMNISJ3XRX8VbITO0VMOPbzGXLsagsg9+LI1WvFWeuiRvUB0LKe1x5/B4epx+0oNbPPEwPcKLN466aCoT5HFofOETQaRKtVltL54UPcCHhUsgQGJI1/qk8PC+wF1pCpc=,iv:ZBC5PcXEA2ERfDq4pWRzGL6uWGxZkU/BqCN/sMdmVoo=,tag:7BlPJIlRCNvGoNWwHO2Dmw==,type:str]
    pgp:
        - created_at: "2025-05-14T01:50:16Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DW7pTteVLMFESAQdALxp+A6LXHXNNajgreznenoQV3GlUKI6Kh3AVb+ScoHYw
            ZTF/XgKWZ9JC0VeJRfT0qBVAXTJVEUIob1dwTN5Ku3n+pBC+J7HwuO7gtN0rZA+J
            1GgBCQIQJoxqLtRmHgk4XN44URAfe6x9aHglU9Z39IJ/G7IhF4qQZVfbqMuBwkjC
            oILlaRO4fZKSi7FJXUrmz0IaSb49Tob9mCNGikyNEpfkj2OkvPDpfsC7tYwRpimu
            acLPXEzdL2FchQ==
            =rLAv
            -----END PGP MESSAGE-----
          fp: CFDDC2FC81DEE54D1C4BFF58538305FABF463DE5
    unencrypted_suffix: _unencrypted
    version: 3.9.4
