freshrss:
    apikey: ENC[AES256_GCM,data:8f1jQMCfgYZ4yW/qu1I=,iv:bSSYoaljZ/byDTGLusyGYAatd2BT4AKbLeN6Eym6aFI=,tag:MopqKjiZ47tPEPswsMHBOQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nkjg6grfv5hjxfpav4k2w3y4t7p7j2gk34huu7cjrkrvrdun05mst0rtal
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2OUlLeWJEejJwMlJRdGlV
            OEVNUEhOT2NyVlRYL2xieC9kd3JMMy9BNnpzCnRydkgrSjVCcDVqcXFPRkxwQkhV
            T2dhWTZtVHdBaHNzNm9EUEsxbHp6U1EKLS0tIEx5KzMwYnp1NzJLWE1kd1NrdVU5
            alVrcGhMQU95ZU5ZZC9KZHZPbWsyb1UKMViWaqvb54n8AKLza/DDUZNQ8ANuJJHr
            gnQ8TRfqPRVGGx9Vev/ZgTClwFiQtBVmshn48ia6uthbTaf9LFi4/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-14T01:51:17Z"
    mac: ENC[AES256_GCM,data:kutoU7ix3v2cxVHsAb2GdQvkqV+21U3jR7w6twstK2uwwh4yOtiLvhplx2ybmJ0Lwkr7qFC/OhLsu2/F5evO03ILjWdf7HJJ/sJ2qPPApMWKXvXx4zSydbBpxtFZ8Vg6zh7tgsLg82y5wi1h88nNcD47jXue8Dpk9KFJsUVphj0=,iv:oYYJLpHNREt0B88w5ReEH5qaR0jgwv4ZP0nl/305mhI=,tag:DkshiPJiqyiwG+U6hjj3UA==,type:str]
    pgp:
        - created_at: "2025-05-14T01:50:16Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DW7pTteVLMFESAQdALxp+A6LXHXNNajgreznenoQV3GlUKI6Kh3AVb+ScoHYw
            ZTF/XgKWZ9JC0VeJRfT0qBVAXTJVEUIob1dwTN5Ku3n+pBC+J7HwuO7gtN0rZA+J
            1GgBCQIQJoxqLtRmHgk4XN44URAfe6x9aHglU9Z39IJ/G7IhF4qQZVfbqMuBwkjC
            oILlaRO4fZKSi7FJXUrmz0IaSb49Tob9mCNGikyNEpfkj2OkvPDpfsC7tYwRpimu
            acLPXEzdL2FchQ==
            =rLAv
            -----END PGP MESSAGE-----
          fp: CFDDC2FC81DEE54D1C4BFF58538305FABF463DE5
    unencrypted_suffix: _unencrypted
    version: 3.9.4
