freshrss:
    apikey: ENC[AES256_GCM,data:8f1jQMCfgYZ4yW/qu1I=,iv:bSSYoaljZ/byDTGLusyGYAatd2BT4AKbLeN6Eym6aFI=,tag:MopqKjiZ47tPEPswsMHBOQ==,type:str]
weatherapi:
    apikey.json: ENC[AES256_GCM,data:IxAoeDvSwEWbXT6cpVz0TAd9aV51cA4Om4zWLGabE4IeE4GIV7etENZJeAiUQQ7Xr5LCSTkTAjx5,iv:MiquMnYblV/KULtScXshZrDf27Vv3euNMO0IUToPS9A=,tag:MsQoWjlq8TgXJf444BRVNw==,type:str]
wolfegideongmail:
    client_id: ENC[AES256_GCM,data:8bNijLKJP+2FCIsrlKHl1ckLY8B7giZHtdCnnTwcykwHjQtiXOid45Xi93smiWPReSZfqDQG2tOADcfA1N48HvJRWTf3hjIX,iv:LY18zWLVrHx2zoTv7H4QNeBQr2VuQ3XPRL0MLHpTcr8=,tag:AteziKY6m4XcchmKGbICRQ==,type:str]
    client_secret: ENC[AES256_GCM,data:PyiMEn7bvQCV0PIVdB2BNsBO+bluj4mc6w1v31x4YtbdF1Y=,iv:gabCJQzDayhrNBSULb26GA+SZZbyus51RSnqskcKVzA=,tag:bC0zgB8R2mbWPaWGFmvmzA==,type:str]
    mbsync_password: ENC[AES256_GCM,data:gzew1eQ1AdEaP1VxOnKg3lLdfQ==,iv:PB2ch8pSybpZLFDgdxEKexPqWJJvnJnPb1NkfQnNxkw=,tag:mCyi2UE55G3jyFuMvKYEUA==,type:str]
gideonwolfexyz:
    mbsync_password: ENC[AES256_GCM,data:mSn9L2LvxQUnT411PWg=,iv:a1P2SXvBWhwWTRN4tZMuanaxH+fI0LaJHso+zMhgDDI=,tag:+Hde2AvzaLrGCJ4soYzyhQ==,type:str]
gideonwolfecom:
    mbsync_password: ENC[AES256_GCM,data:ZkrfDSpWOPlLtYdq,iv:uAlbeYGeau1uE97QxvEpS88np9l5suSyy3BCOVYvifc=,tag:UK4YUmQBKEmJPbE+ZkzPzw==,type:str]
irc:
    libera:
        nick: ENC[AES256_GCM,data:nsPC9rv4L1Vl,iv:M4GrQs4k5wSKLwzX8RH/L6elKOyzcHpjdZRNAwOw5ps=,tag:hdu55i5IX2PU+t9tRcLiUw==,type:str]
        password: ENC[AES256_GCM,data:F9YbSMWrNGy/Y058vds=,iv:qxupWXOIfj9amybBfkx6Zo3mQYqvReYNk/8DOAtiC4Q=,tag:WKAgmANnOEBv3RnPxYOH5A==,type:str]
    weechat:
        sec.conf: ENC[AES256_GCM,data:2Wx3sMGBa/ZBqYPaeKzoGQcPbuuRASVwBgY4pd2XD61cswdDFFgifFOkxixsuvfhpjlUvyYHoBob00QfKZ/KwmTudAfoBvNUFyKTSv6QU+l7nTllkUFbmHLLCV+IaTgo3xbHmqvtZNjGwbWpKi7el4/89Dn1toF1tnmnIk+n3ZAF+Ch8,iv:gcjE7OkFT2LsC46LVzS8kWoVwJyVh4K1VZJ/26HKzIw=,tag:F8K1tKOFkn49jqlSjm4O6A==,type:str]
termsonic:
    termsonic.toml: ENC[AES256_GCM,data:hePpk2l/LB64f1OHQY9fsg0nXmgDcIB3FF52t+bZPmLQQI6QM6ShxLKhEVir5IqytwGfh9r5jYFVvrMKHXRUYLrzNgbTPccgtXf3Cnu0sra4GtdzNX/Icw==,iv:u3P1cv4huxTffbxwztFAMAQiLc+Y0AtBU0i4iyihqvw=,tag:9yjCp3WT1d9UJZI5KoLaqg==,type:str]
ssh:
    gideon_ssh_sk:
        private_key: ENC[AES256_GCM,data:bY1Y9KkJZHG5rmtVgJIDOc3u72YMOS5mNBkO44zidSaImAi7zpbYcQJiwPLbE9ZI9HOC1GMx5gwYj2cMSPdGcaxH2CoOwx8bsRErW6fgwwjdkwdFIReBZwLyhaE6lR9gIOo04uqiLTnYfuOm4waFOx9N7Fc7kqBUek6PTogGP4za8tsN5h+GmjJP7Ie7Iq/FOUrQRm+RudETILGtirbzzY3k5waZIVQXsuJDn1DhSvnkOwaTVmLlyHDp1aNKhQvjWv/zX4G+BgOpq6PbCtcgBSwg673wTNjfEG+lWkSsvVZ69yppS0JPBv4E90e5gHqqRD8AxJymmWEGo0/3jRAwsRLmmWUstSgekr53ZfhqA8Jq9S63P7vSbnGKTHZNy9X/1DmfWPSPRgU6qqkF9lec5ZUJanV42A2YHd7W4F+pByt4GRKnugwRD/vfHBd5FeMsOMhTW0MqyGDnMH4hs0yaKdUQVYMsHh8npPN7eITq68lXSv/zZf7yE4g74P0KCaoauA9WjtLsyHdW1UJSY395ysSrBp1moohWevyuv9TbA2i8bvzdqJIG6qrAagkoYhgpdqF7S/bexh4svnVHbO/abYTcV2N98p+3uedcAsFwPa3kT81bCMvHfw==,iv:4hX4xSA5k57VaTzocOujZuEzVFzr+GwhBzvISlzf9yI=,tag:4b/t3naGklxdU+5hed4vKg==,type:str]
sops:
    age:
        - recipient: age10exe2vqxqapa87r7xxyrzessgk9efjac05s3znsl66xzfm6pqgpqp6793w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvcjRVNHVNTWZCL3FxZVY1
            MjR0cGlLZUVCRUJDQ1ZmamI4ZWxxbzVzbVFBCmVRempiNUhOalVuTDM4MEMwZ2Y5
            ZnoxUXdDQitqY2ZCbG1ad0RLelZvN1UKLS0tIFFrczRoRkp5WlA1bXBLeml2T25y
            cWVHQmFSM25qeXZzaytDVUUzSGNabm8Kfe0EFdpbRhgk1DEUXafVtfIqN6xoyFgU
            xdzkVU6+q4M3i4tdSQNQN1pXyAX2mIJC+USy2srPIEqAUyURbEM+dw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nkjg6grfv5hjxfpav4k2w3y4t7p7j2gk34huu7cjrkrvrdun05mst0rtal
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArcFZSdXo2WWY3RzJySVJi
            OG1KKzdLQW55K2VKT0NhQ2RXOEdYSVhuSlNVCjJwdWFxVENaSXgyWlEzWFEvemhT
            S1QrWG1PMkp4WXMzVmVta2NpK1VNcUUKLS0tIGtvaVJ3RldrR0I4WTlNeUo2djYz
            amhIYlhtVG81aFRGdUdrNTlQWjZaK2MKUWUc64L7CBScW+BGBrIES31/2eddMCjt
            RLZhQxFa1QSwKF59M0jTnbmS2epv55bylD9s6vACJWusPr2WrOfEUw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yyzawdy20cynpv4pzy3a36lsykxu733e0g4cwvmjnvaup64s8swscxhhst
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZeU10d3JzcG1WZFg3L1lU
            V21wQ2tpSFpFUUFWTC9MclFQSXRZT1J4azFRCkMvZXFyYytzY2RtSXZrVWx4aTBF
            dVNnTHp0UHE2ckk2MWxma2RWV0xuY2cKLS0tIE1OSHpwYlFEUFllejBWZkdPUHZK
            QlU4ckRlQzhCcEJnYWUxMXFtYTBKUHMKhwzJoHX0DuE+Twdb+nJhmGA4XLLmODsE
            c6h/jxPo7g20JzwTQGqpUBMhdAjZpBAwoKh7baO/XEu15PcZGljbMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-14T17:20:59Z"
    mac: ENC[AES256_GCM,data:W+oxHLxdaZ5sXP3itWPRcsJQWVavh18g3UQcWJScDbTbldcftFhD1eVeoyMALXSbQvQeBN1MFL/G1aoY9VR3W2wtlpkNefA6DXDk+ofKomDuzfsru3kaW1f2iN+2S/J8AmdPRuGOx5OFm4g0vhosQGnZf7UEeRmPa8FRzMlzaFk=,iv:uLHLfjdGgjr6mU9pevZalEJdiEC0RZLaX8wVnSP6XBE=,tag:83lqdpoO3lq/zSkdxEEJwA==,type:str]
    pgp:
        - created_at: "2025-05-24T19:37:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DW7pTteVLMFESAQdAseoU7evpfcylfsgGGgHGWjCsV/NeCUT/XOdvGRbKoWUw
            P3+4jkAjHTOQc1wvoXYKpdb0C6CemNbAKkC6h+dDCzg8rDeqGByq3j9WBguMyu0R
            0l4B5DHVOpKB7PphPDeyiZI4LdL2mgUhhS8K55QF+WtHv/zwMAwghsr5+lZa/1Gr
            kHP7v0nhbujUH9R43on46bejMozhGQCuhINslskHFqxBpSZj0GdMAQDnGHel7TVU
            =DEvY
            -----END PGP MESSAGE-----
          fp: CFDDC2FC81DEE54D1C4BFF58538305FABF463DE5
    unencrypted_suffix: _unencrypted
    version: 3.9.4
