hello: ENC[AES256_GCM,data:YzJDHdVWKDrkCecSdk16HiHywxXgMrfeNE0cq0VHqDdp2J7g6H/vdr318MKHIg==,iv:X7w/HiyOlDgdzwETs7JCDcZqewifMwdNNlgPK/uEt0E=,tag:IqNOde2ffjkmRNpYd2CzRQ==,type:str]
freshrss:
    apikey: ENC[AES256_GCM,data:4mjsOSC4hrVcTWn7JJ0=,iv:6GAMRux7t/k93NrbvsY9MV0BXdaWcXeKmiOeRUIFJVA=,tag:4q0lDsBTFqASx4yzmDIUgQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nkjg6grfv5hjxfpav4k2w3y4t7p7j2gk34huu7cjrkrvrdun05mst0rtal
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyTWl2ZTRWb2kwSVlMZnI5
            ZXJpZXAwTkpJTTl3UWJmSVdJaE5kMDF5WFFBCkVJNy9EYVdIaitkNFFueW43dFVL
            R3NrWnZ0K0tuWTgwRzUyT0NKcXZpYkEKLS0tIHQxcTE5cWlTUGQ5bHNMVkFKUWI3
            cDRDa0NDTVVValgzcnhzL3FTM2wxYnMKNtIEslYCMN8FOi1d/yTEbZrSJE7MfCU4
            QE3ZtLZOuU2nO2UZoCoAZXQBwlYNAJdFYHieehrPAcE01jAZi0/5VQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-14T00:55:38Z"
    mac: ENC[AES256_GCM,data:Q0E+Y71/fcv2/0aJf94IQerhcd7K0Ml60XQo62SvTZRNqZVhAKQr2UcUY+G9znGS2HOUG1/fTKuMip837m13qtW2SUNHF2+mvVInpoA5f+2qm1pv2UHdypPlB/6liuYnUwy5uZHZPSmFDg+pB6ddXTU8d/NQ19lhv6T4Rj8qCGI=,iv:RHVi2EEFj+Eq86mNy18n4IbFgyozrDopy0xY5XQp5W4=,tag:y9ExfkS1pEyRo7gtBf1Z3Q==,type:str]
    pgp:
        - created_at: "2025-05-14T00:17:05Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DW7pTteVLMFESAQdAl8cGCkZ9B/idsOlEFaE8c9qLUkkZr4/30M1csNYX6GYw
            lyY53v5IbTVoh13Vbrync3uScBjRuu92i+yW2cBSpwT80oamZT3KRGwpbtSDpTsl
            1GgBCQIQYXJcXd9Ei75vz0vAcdepw6MSymGk0bgCtqI533r3PzK8UJg19iEPaluO
            ENXG1utDridwaULSPV6+FUuiorD3hEbP2APbpIRGWnMMmhZkV1NLbsnbJeYXAs1o
            P5T6MrxKazEqnA==
            =FH2L
            -----END PGP MESSAGE-----
          fp: CFDDC2FC81DEE54D1C4BFF58538305FABF463DE5
    unencrypted_suffix: _unencrypted
    version: 3.9.4
