hello: ENC[AES256_GCM,data:1h95LlVbsKZ+9plEQw8P+ZV2DCOVSr5NjUWCAJl9eTolz/EPGc5lJOdP6IqSJA==,iv:VShoqPOUJWiQpDvh2uodosuiv1iB88TNwIwZdl9QAm8=,tag:3DYlUKQB1u9P2TqOsrFhZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wrxmxqqq5l25uvrf3hjxya34mxk3xhhn86vuwf7n8mnm7gkajdps0natng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzRkdzQlJ4NUt2ZDdRSFU0
            ZXB5dU9lbGw4L1hrdjRxcFVXRjNGN3pFblY4Cnkrd3NWRDFrK3lnUU82Z01nWjNq
            ZmxVUEhKTkJYQW9kR1p4a3dTRnI4cEUKLS0tIHpoTXhsUFJqSWFUdHc5NnpGVU5U
            Qys0ejNxZHRaaEJBa1NEbmhITFVuNTAKeSyJ+GtaRQSoCOF2iA8Y51AV1bAtOHwg
            p8/4Xo9Y3cUv42INaeZ5OHyZRMo66hAoDUX3LbfOv6Ccx+4R3q5xUQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nkjg6grfv5hjxfpav4k2w3y4t7p7j2gk34huu7cjrkrvrdun05mst0rtal
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4L3NudlZlenAzUGhtUlgy
            aVZMZVV6bGovR0NJZzFBZnZWVHdaNExPZkZ3CnBNN1VWSjFORmxteGM3OXA1WERl
            Sm5uYkVXVzk4WklRUGlyem9DRHZ0MWcKLS0tIFMrQ1lpTXJESThZNkNCdjZCcHA0
            bzRWSDdUMDA1MnkxVGFLVDZ6U1o5QXcKPa4geVEaEaHYKMBSqFt7jDAJYwEnGBBH
            +j0F6QWTcEl6nJvyg4ODulDSfslRf5Ge5sFvDpVBabzL5GNOe8qiNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-09T05:34:08Z"
    mac: ENC[AES256_GCM,data:+mL8DR587KhSbYOmWsy6jKP+tVGExwZ7s9nMjemumH3sho8cDVauMuGsIjADrxjL4+EI2vWQLdvbuoavdgDzps65KoCHY9ud3iambB3GudivdlpTa4gWHaVhSAMNmBSUOw6yoLXQtf2CHyU2F0SpG15xFSqHqGbJ5aBbUemJN0E=,iv:5UI7tJL98f26qtjXQT3kKR4UIug3g239hjx5VCOkBYg=,tag:m1+1YSME5xQJ0ZXCsCIrUg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
