{ pkgs, lib, config, ... }:

with config.lib.stylix.colors.withHashtag;

{

  home.file.blender-stylix-theme = {
    #xdg.configFile.blender-stylix-theme = {
    enable = true;
    target = ".config/blender/4.2/scripts/presets/interface_theme/stylix.xml";
    # TODO: Use builtins.toXML for this
    text = ''
      <bpy>
        <Theme>
          <user_interface>
            <ThemeUserInterface
              menu_shadow_fac="0.4"
              menu_shadow_width="5"
              icon_alpha="1"
              icon_saturation="1"
              widget_emboss="${base01}00"
              editor_outline="${base00}"
              widget_text_cursor="${base0E}"
              panel_roundness="0.8"
              transparent_checker_primary="${base01}"
              transparent_checker_secondary="${base00}"
              transparent_checker_size="8"
              axis_x="${base08}"
              axis_y="${base0B}"
              axis_z="${base07}"
              gizmo_hi="${base05}"
              gizmo_primary="${base0A}"
              gizmo_secondary="${base0C}"
              gizmo_view_align="${base04}"
              gizmo_a="${base08}"
              gizmo_b="${base0C}"
              icon_scene="${base05}ff"
              icon_collection="${base05}ff"
              icon_object="${base09}ff"
              icon_object_data="${base0B}ff"
              icon_modifier="${base07}ff"
              icon_shading="${base08}ff"
              icon_folder="${base0A}ff"
              icon_border_intensity="0"
              >
              <wcol_regular>
                <ThemeWidgetColors
                  outline="${base00}"
                  inner="${base00}ff"
                  inner_sel="${base0E}ff"
                  item="${base05}ff"
                  text="${base05}"
                  text_sel="${base00}"
                  show_shaded="FALSE"
                  shadetop="0"
                  shadedown="0"
                  roundness="0.8"
                  >
                </ThemeWidgetColors>
              </wcol_regular>
              <wcol_tool>
                <ThemeWidgetColors
                  outline="${base00}"
                  inner="${base00}ff"
                  inner_sel="${base0E}ff"
                  item="${base05}ff"
                  text="${base05}"
                  text_sel="${base00}"
                  show_shaded="FALSE"
                  shadetop="0"
                  shadedown="0"
                  roundness="0.8"
                  >
                </ThemeWidgetColors>
              </wcol_tool>
              <wcol_toolbar_item>
                <ThemeWidgetColors
                  outline="${base00}"
                  inner="${base00}ff"
                  inner_sel="${base0E}ff"
                  item="${base05}ff"
                  text="${base05}"
                  text_sel="${base00}"
                  show_shaded="FALSE"
                  shadetop="0"
                  shadedown="0"
                  roundness="0.8"
                  >
                </ThemeWidgetColors>
              </wcol_toolbar_item>
              <wcol_radio>
                <ThemeWidgetColors
                  outline="${base00}"
                  inner="${base00}ff"
                  inner_sel="${base0E}ff"
                  item="${base05}ff"
                  text="${base05}"
                  text_sel="${base00}"
                  show_shaded="FALSE"
                  shadetop="0"
                  shadedown="0"
                  roundness="0.8"
                  >
                </ThemeWidgetColors>
              </wcol_radio>
              <wcol_text>
                <ThemeWidgetColors
                  outline="${base00}"
                  inner="${base00}ff"
                  inner_sel="${base00}ff"
                  item="${base0E}ff"
                  text="${base05}"
                  text_sel="${base05}"
                  show_shaded="FALSE"
                  shadetop="0"
                  shadedown="0"
                  roundness="0.8"
                  >
                </ThemeWidgetColors>
              </wcol_text>
              <wcol_option>
                <ThemeWidgetColors
                  outline="${base00}"
                  inner="${base00}ff"
                  inner_sel="${base0E}ff"
                  item="${base00}ff"
                  text="${base05}"
                  text_sel="${base05}"
                  show_shaded="FALSE"
                  shadetop="0"
                  shadedown="0"
                  roundness="1"
                  >
                </ThemeWidgetColors>
              </wcol_option>
              <wcol_toggle>
                <ThemeWidgetColors
                  outline="${base00}"
                  inner="${base00}ff"
                  inner_sel="${base0E}ff"
                  item="${base05}ff"
                  text="${base05}"
                  text_sel="${base00}"
                  show_shaded="FALSE"
                  shadetop="0"
                  shadedown="0"
                  roundness="0.8"
                  >
                </ThemeWidgetColors>
              </wcol_toggle>
              <wcol_num>
                <ThemeWidgetColors
                  outline="${base00}"
                  inner="${base00}ff"
                  inner_sel="${base01}ff"
                  item="${base0E}ff"
                  text="${base05}"
                  text_sel="${base00}"
                  show_shaded="FALSE"
                  shadetop="0"
                  shadedown="0"
                  roundness="0.8"
                  >
                </ThemeWidgetColors>
              </wcol_num>
              <wcol_numslider>
                <ThemeWidgetColors
                  outline="${base00}"
                  inner="${base00}ff"
                  inner_sel="${base00}ff"
                  item="${base0E}ff"
                  text="${base05}"
                  text_sel="${base05}"
                  show_shaded="FALSE"
                  shadetop="0"
                  shadedown="0"
                  roundness="0.8"
                  >
                </ThemeWidgetColors>
              </wcol_numslider>
              <wcol_box>
                <ThemeWidgetColors
                  outline="${base0E}"
                  inner="${base01}ff"
                  inner_sel="${base0E}ff"
                  item="${base05}ff"
                  text="${base05}"
                  text_sel="${base05}"
                  show_shaded="FALSE"
                  shadetop="0"
                  shadedown="0"
                  roundness="0.8"
                  >
                </ThemeWidgetColors>
              </wcol_box>
              <wcol_menu>
                <ThemeWidgetColors
                  outline="${base00}"
                  inner="${base00}ff"
                  inner_sel="${base0E}ff"
                  item="${base05}ff"
                  text="${base05}"
                  text_sel="${base00}"
                  show_shaded="FALSE"
                  shadetop="0"
                  shadedown="0"
                  roundness="0.8"
                  >
                </ThemeWidgetColors>
              </wcol_menu>
              <wcol_pulldown>
                <ThemeWidgetColors
                  outline="${base00}"
                  inner="${base00}ff"
                  inner_sel="${base0E}ff"
                  item="${base05}ff"
                  text="${base05}"
                  text_sel="${base00}"
                  show_shaded="FALSE"
                  shadetop="0"
                  shadedown="0"
                  roundness="0.8"
                  >
                </ThemeWidgetColors>
              </wcol_pulldown>
              <wcol_menu_back>
                <ThemeWidgetColors
                  outline="${base08}"
                  inner="${base01}ff"
                  inner_sel="${base0E}ff"
                  item="${base05}ff"
                  text="${base05}"
                  text_sel="${base05}"
                  show_shaded="FALSE"
                  shadetop="0"
                  shadedown="0"
                  roundness="1"
                  >
                </ThemeWidgetColors>
              </wcol_menu_back>
              <wcol_pie_menu>
                <ThemeWidgetColors
                  outline="${base00}"
                  inner="${base00}ff"
                  inner_sel="${base0E}ff"
                  item="#65527bff"
                  text="${base05}"
                  text_sel="${base00}"
                  show_shaded="FALSE"
                  shadetop="0"
                  shadedown="0"
                  roundness="0.8"
                  >
                </ThemeWidgetColors>
              </wcol_pie_menu>
              <wcol_tooltip>
                <ThemeWidgetColors
                  outline="${base05}"
                  inner="${base05}ff"
                  inner_sel="${base0E}ff"
                  item="${base00}ff"
                  text="${base00}"
                  text_sel="${base00}"
                  show_shaded="FALSE"
                  shadetop="0"
                  shadedown="0"
                  roundness="0.8"
                  >
                </ThemeWidgetColors>
              </wcol_tooltip>
              <wcol_menu_item>
                <ThemeWidgetColors
                  outline="${base01}"
                  inner="${base01}ff"
                  inner_sel="${base0E}ff"
                  item="${base05}ff"
                  text="${base05}"
                  text_sel="${base00}"
                  show_shaded="FALSE"
                  shadetop="0"
                  shadedown="0"
                  roundness="0.8"
                  >
                </ThemeWidgetColors>
              </wcol_menu_item>
              <wcol_scroll>
                <ThemeWidgetColors
                  outline="${base00}"
                  inner="${base00}ff"
                  inner_sel="${base00}ff"
                  item="#9399b2ff"
                  text="${base05}"
                  text_sel="${base05}"
                  show_shaded="FALSE"
                  shadetop="0"
                  shadedown="0"
                  roundness="1"
                  >
                </ThemeWidgetColors>
              </wcol_scroll>
              <wcol_progress>
                <ThemeWidgetColors
                  outline="${base00}"
                  inner="${base00}ff"
                  inner_sel="${base0E}ff"
                  item="${base0E}ff"
                  text="${base05}"
                  text_sel="${base05}"
                  show_shaded="FALSE"
                  shadetop="0"
                  shadedown="0"
                  roundness="0.8"
                  >
                </ThemeWidgetColors>
              </wcol_progress>
              <wcol_list_item>
                <ThemeWidgetColors
                  outline="${base01}"
                  inner="${base01}ff"
                  inner_sel="${base00}ff"
                  item="${base0E}ff"
                  text="${base05}"
                  text_sel="${base05}"
                  show_shaded="FALSE"
                  shadetop="0"
                  shadedown="0"
                  roundness="0.8"
                  >
                </ThemeWidgetColors>
              </wcol_list_item>
              <wcol_view_item>
                <ThemeWidgetColors
                  outline="${base00}"
                  inner="${base00}ff"
                  inner_sel="${base0E}ff"
                  item="#585b70ff"
                  text="${base05}"
                  text_sel="${base05}"
                  show_shaded="FALSE"
                  shadetop="0"
                  shadedown="0"
                  roundness="0.8"
                  >
                </ThemeWidgetColors>
              </wcol_view_item>
              <wcol_state>
                <ThemeWidgetStateColors
                  inner_anim="#519542"
                  inner_anim_sel="${base0B}"
                  inner_key="#c97f19"
                  inner_key_sel="${base0A}"
                  inner_driven="#7746b7"
                  inner_driven_sel="${base0E}"
                  inner_overridden="#51bac0"
                  inner_overridden_sel="${base0C}"
                  inner_changed="#c8510c"
                  inner_changed_sel="${base09}"
                  blend="0.5"
                  >
                </ThemeWidgetStateColors>
              </wcol_state>
              <wcol_tab>
                <ThemeWidgetColors
                  outline="${base00}"
                  inner="${base00}ff"
                  inner_sel="#585b70ff"
                  item="${base05}ff"
                  text="${base05}"
                  text_sel="${base05}"
                  show_shaded="FALSE"
                  shadetop="0"
                  shadedown="0"
                  roundness="0.8"
                  >
                </ThemeWidgetColors>
              </wcol_tab>
            </ThemeUserInterface>
          </user_interface>
          <view_3d>
            <ThemeView3D
              grid="${base01}80"
              clipping_border_3d="#3f3f3fff"
              wire="#b7b7ff"
              wire_edit="${base01}"
              edge_width="1"
              gp_vertex="#b7b7ff"
              gp_vertex_select="${base0E}"
              gp_vertex_size="3"
              text_grease_pencil="#b5e61d"
              object_selected="#65527b"
              object_active="${base0E}"
              text_keyframe="#ddd700"
              camera="${base05}"
              empty="${base05}"
              light="${base05}50"
              speaker="${base05}"
              vertex="${base05}"
              vertex_select="${base0E}"
              vertex_active="${base01}"
              vertex_size="3"
              vertex_bevel="#00a5ff"
              vertex_unreferenced="${base01}"
              edge_select="${base0E}"
              edge_seam="#db2512"
              edge_sharp="#00ffff"
              edge_crease="#cc0099"
              edge_bevel="#00a5ff"
              edge_facesel="#4b4b4b"
              freestyle_edge_mark="#7fff7f"
              face="${base05}02"
              face_select="${base0E}2e"
              face_dot="${base0E}"
              facedot_size="3"
              freestyle_face_mark="#7fff7f4d"
              face_retopology="#50c8ff0f"
              face_back="#ff0000b3"
              face_front="#0000ffb3"
              nurb_uline="#909000"
              nurb_vline="#803060"
              nurb_sel_uline="#f0ff40"
              nurb_sel_vline="#f090a0"
              act_spline="#db2512"
              handle_free="${base01}"
              handle_auto="#909000"
              handle_vect="#409030"
              handle_sel_vect="#40c030"
              handle_align="#803060"
              handle_sel_free="${base01}"
              handle_sel_auto="#f0ff40"
              handle_sel_align="#f090a0"
              lastsel_point="${base05}"
              extra_edge_len="#150806"
              extra_edge_angle="#4d4d00"
              extra_face_angle="#0000cc"
              extra_face_area="#004d00"
              editmesh_active="${base05}33"
              normal="#22dddd"
              vertex_normal="#2361dd"
              split_normal="#dd23dd"
              bone_pose="#50c8ff"
              bone_pose_active="#8cffff"
              bone_solid="#b2b2b2"
              bone_locked_weight="#ff000080"
              bundle_solid="#c8c8c8"
              camera_path="${base01}"
              camera_passepartout="${base01}"
              skin_root="#b44d4d"
              view_overlay="${base01}"
              transform="${base05}"
              frame_current="#4772b3"
              paint_curve_handle="#7fff7f7f"
              paint_curve_pivot="#ff7f7f7f"
              outline_width="1"
              object_origin_size="6"
              >
              <space>
                <ThemeSpaceGradient
                  title="${base05}"
                  text="${base05}"
                  text_hi="${base05}"
                  header="${base00}00"
                  header_text="${base05}"
                  header_text_hi="${base05}"
                  button="${base00}00"
                  button_title="${base05}"
                  button_text="${base05}"
                  button_text_hi="${base05}"
                  navigation_bar="${base00}ff"
                  execution_buts="${base00}ff"
                  tab_active="${base04}"
                  tab_inactive="${base00}"
                  tab_back="${base00}ff"
                  tab_outline="${base00}"
                  >
                  <gradients>
                    <ThemeGradientColors
                      background_type="RADIAL"
                      high_gradient="${base00}"
                      gradient="${base01}"
                      >
                    </ThemeGradientColors>
                  </gradients>
                  <panelcolors>
                    <ThemePanelColors
                      header="${base01}ff"
                      back="${base01}ff"
                      sub_back="${base01}ff"
                      >
                    </ThemePanelColors>
                  </panelcolors>
                </ThemeSpaceGradient>
              </space>
            </ThemeView3D>
          </view_3d>
          <graph_editor>
            <ThemeGraphEditor
              grid="${base00}"
              frame_current="#89b4fa"
              time_scrub_background="${base00}ff"
              time_marker_line="${base05}ff"
              time_marker_line_selected="${base0E}ff"
              window_sliders="#969696"
              channels_region="${base00}"
              dopesheet_channel="${base00}"
              dopesheet_subchannel="${base00}"
              channel_group="${base00}"
              active_channels_group="${base00}"
              preview_range="#a14d0066"
              vertex="${base05}"
              vertex_select="#65527b"
              vertex_active="${base0E}"
              vertex_size="6"
              vertex_bevel="${base05}"
              vertex_unreferenced="${base05}"
              handle_free="${base05}"
              handle_auto="#909000"
              handle_vect="#409030"
              handle_sel_vect="#40c030"
              handle_align="#803060"
              handle_sel_free="${base05}"
              handle_sel_auto="#f0ff40"
              handle_sel_align="#f090a0"
              handle_auto_clamped="#994030"
              handle_sel_auto_clamped="#f0af90"
              lastsel_point="${base05}"
              handle_vertex="${base05}"
              handle_vertex_select="${base0E}"
              handle_vertex_size="5"
              >
              <space>
                <ThemeSpaceGeneric
                  back="${base00}"
                  title="${base05}"
                  text="${base05}"
                  text_hi="${base05}"
                  header="${base00}ff"
                  header_text="${base05}"
                  header_text_hi="${base05}"
                  button="${base00}ff"
                  button_title="${base05}"
                  button_text="${base05}"
                  button_text_hi="${base05}"
                  navigation_bar="${base00}ff"
                  execution_buts="${base00}ff"
                  tab_active="${base04}"
                  tab_inactive="${base00}"
                  tab_back="${base00}ff"
                  tab_outline="${base00}"
                  >
                  <panelcolors>
                    <ThemePanelColors
                      header="${base01}ff"
                      back="${base01}ff"
                      sub_back="${base01}ff"
                      >
                    </ThemePanelColors>
                  </panelcolors>
                </ThemeSpaceGeneric>
              </space>
              <space_list>
                <ThemeSpaceListGeneric
                  list="${base00}"
                  list_title="${base05}"
                  list_text="${base05}"
                  list_text_hi="${base0E}"
                  >
                </ThemeSpaceListGeneric>
              </space_list>
            </ThemeGraphEditor>
          </graph_editor>
          <file_browser>
            <ThemeFileBrowser
              selected_file="${base0E}"
              row_alternate="${base01}45"
              >
              <space>
                <ThemeSpaceGeneric
                  back="${base00}"
                  title="${base05}"
                  text="${base05}"
                  text_hi="${base05}"
                  header="${base00}ff"
                  header_text="${base05}"
                  header_text_hi="${base05}"
                  button="${base00}ff"
                  button_title="${base05}"
                  button_text="${base05}"
                  button_text_hi="${base05}"
                  navigation_bar="${base00}ff"
                  execution_buts="${base00}ff"
                  tab_active="${base04}"
                  tab_inactive="${base00}"
                  tab_back="${base00}ff"
                  tab_outline="${base00}"
                  >
                  <panelcolors>
                    <ThemePanelColors
                      header="${base01}ff"
                      back="${base01}ff"
                      sub_back="${base01}ff"
                      >
                    </ThemePanelColors>
                  </panelcolors>
                </ThemeSpaceGeneric>
              </space>
            </ThemeFileBrowser>
          </file_browser>
          <nla_editor>
            <ThemeNLAEditor
              grid="${base00}"
              view_sliders="#969696"
              dopesheet_channel="${base00}"
              nla_track="${base00}"
              active_action="${base00}66"
              active_action_unset="${base00}4d"
              preview_range="#a14d0066"
              strips="#0d0d0d"
              strips_selected="${base0E}"
              transition_strips="#1c2630"
              transition_strips_selected="#2e75db"
              meta_strips="#332642"
              meta_strips_selected="#692196"
              sound_strips="#2b3d3d"
              sound_strips_selected="#1f7a7a"
              tweak="#4df31a"
              tweak_duplicate="#d90000"
              keyframe_border="${base01}ff"
              keyframe_border_selected="${base01}ff"
              frame_current="#89b4fa"
              time_scrub_background="${base00}ff"
              time_marker_line="${base05}4d"
              time_marker_line_selected="${base05}b3"
              >
              <space>
                <ThemeSpaceGeneric
                  back="${base00}"
                  title="${base05}"
                  text="${base05}"
                  text_hi="${base05}"
                  header="${base00}ff"
                  header_text="${base05}"
                  header_text_hi="${base05}"
                  button="${base00}ff"
                  button_title="${base05}"
                  button_text="${base05}"
                  button_text_hi="${base05}"
                  navigation_bar="${base00}ff"
                  execution_buts="${base00}ff"
                  tab_active="${base04}"
                  tab_inactive="${base00}"
                  tab_back="${base00}ff"
                  tab_outline="${base00}"
                  >
                  <panelcolors>
                    <ThemePanelColors
                      header="${base01}ff"
                      back="${base01}ff"
                      sub_back="${base01}ff"
                      >
                    </ThemePanelColors>
                  </panelcolors>
                </ThemeSpaceGeneric>
              </space>
              <space_list>
                <ThemeSpaceListGeneric
                  list="${base00}"
                  list_title="${base05}"
                  list_text="${base05}"
                  list_text_hi="${base0E}"
                  >
                </ThemeSpaceListGeneric>
              </space_list>
            </ThemeNLAEditor>
          </nla_editor>
          <dopesheet_editor>
            <ThemeDopeSheet
              grid="${base00}"
              frame_current="#89b4fa"
              time_scrub_background="${base00}ff"
              time_marker_line="${base05}ff"
              time_marker_line_selected="${base0E}ff"
              value_sliders="${base01}"
              view_sliders="#c0c0c0"
              dopesheet_channel="${base00}66"
              dopesheet_subchannel="${base00}66"
              channels="${base00}66"
              channels_selected="${base00}66"
              channel_group="${base00}66"
              active_channels_group="${base00}67"
              long_key="${base05}1f"
              long_key_selected="${base0E}99"
              keyframe="#bfbfbf"
              keyframe_selected="${base0E}"
              keyframe_extreme="#e8b3cc"
              keyframe_extreme_selected="${base08}"
              keyframe_breakdown="#b3dbe8"
              keyframe_breakdown_selected="#54bfed"
              keyframe_jitter="#94e575"
              keyframe_jitter_selected="${base0B}"
              keyframe_movehold="#808080"
              keyframe_movehold_selected="${base0E}"
              keyframe_border="${base01}ff"
              keyframe_border_selected="${base01}ff"
              keyframe_scale_factor="1"
              summary="#4d272766"
              preview_range="#a14d0066"
              interpolation_line="#94e575cc"
              simulated_frames="${base0E}ff"
              >
              <space>
                <ThemeSpaceGeneric
                  back="${base00}"
                  title="${base05}"
                  text="${base05}"
                  text_hi="${base05}"
                  header="${base00}ff"
                  header_text="${base05}"
                  header_text_hi="${base05}"
                  button="${base00}ff"
                  button_title="${base05}"
                  button_text="${base05}"
                  button_text_hi="${base05}"
                  navigation_bar="${base00}ff"
                  execution_buts="${base00}ff"
                  tab_active="${base04}"
                  tab_inactive="${base00}"
                  tab_back="${base00}ff"
                  tab_outline="${base00}"
                  >
                  <panelcolors>
                    <ThemePanelColors
                      header="${base01}ff"
                      back="${base01}ff"
                      sub_back="${base01}ff"
                      >
                    </ThemePanelColors>
                  </panelcolors>
                </ThemeSpaceGeneric>
              </space>
              <space_list>
                <ThemeSpaceListGeneric
                  list="${base00}"
                  list_title="${base05}"
                  list_text="${base05}"
                  list_text_hi="${base0E}"
                  >
                </ThemeSpaceListGeneric>
              </space_list>
            </ThemeDopeSheet>
          </dopesheet_editor>
          <image_editor>
            <ThemeImageEditor
              grid="${base00}ff"
              vertex="${base05}"
              vertex_select="${base0E}"
              vertex_active="${base01}"
              vertex_size="3"
              vertex_bevel="${base01}"
              vertex_unreferenced="${base01}"
              face="${base05}0a"
              face_select="${base0E}3c"
              face_dot="${base0E}"
              facedot_size="3"
              freestyle_face_mark="#7fff7f33"
              face_retopology="${base01}00"
              face_back="${base01}00"
              face_front="${base01}00"
              editmesh_active="${base05}40"
              wire_edit="${base05}"
              edge_width="1"
              edge_select="${base0E}"
              scope_back="#727272ff"
              preview_stitch_face="#7f7f0033"
              preview_stitch_edge="#ff00ff33"
              preview_stitch_vert="#0000ff33"
              preview_stitch_stitchable="#00ff00ff"
              preview_stitch_unstitchable="#ff0000ff"
              preview_stitch_active="#e1d2c323"
              uv_shadow="#707070ff"
              frame_current="#4772b3"
              metadatabg="${base01}"
              metadatatext="${base05}"
              handle_free="${base01}"
              handle_auto="#909000"
              handle_align="#803060"
              handle_sel_free="${base01}"
              handle_sel_auto="#f0ff40"
              handle_sel_align="#f090a0"
              handle_auto_clamped="${base01}"
              handle_sel_auto_clamped="${base01}"
              handle_vertex="${base01}"
              handle_vertex_select="#ffff00"
              handle_vertex_size="5"
              paint_curve_handle="#7fff7f7f"
              paint_curve_pivot="#ff7f7f7f"
              >
              <space>
                <ThemeSpaceGeneric
                  back="${base00}"
                  title="${base05}"
                  text="${base05}"
                  text_hi="${base05}"
                  header="${base00}ff"
                  header_text="${base05}"
                  header_text_hi="${base05}"
                  button="${base00}00"
                  button_title="${base05}"
                  button_text="${base05}"
                  button_text_hi="${base05}"
                  navigation_bar="${base00}ff"
                  execution_buts="${base00}ff"
                  tab_active="${base04}"
                  tab_inactive="${base00}"
                  tab_back="${base00}ff"
                  tab_outline="${base00}"
                  >
                  <panelcolors>
                    <ThemePanelColors
                      header="${base01}ff"
                      back="${base01}ff"
                      sub_back="${base01}ff"
                      >
                    </ThemePanelColors>
                  </panelcolors>
                </ThemeSpaceGeneric>
              </space>
            </ThemeImageEditor>
          </image_editor>
          <sequence_editor>
            <ThemeSequenceEditor
              grid="${base00}"
              window_sliders="#a0a0a0"
              movie_strip="${base07}"
              movieclip_strip="${base08}"
              image_strip="${base09}"
              scene_strip="${base0A}"
              audio_strip="#74c7ec"
              effect_strip="#f5c2e7"
              color_strip="#7f849c"
              meta_strip="#65527b"
              mask_strip="${base0F}"
              text_strip="${base05}"
              active_strip="${base0E}"
              selected_strip="#65527b"
              frame_current="#89b4fa"
              time_scrub_background="${base00}ff"
              time_marker_line="${base05}ff"
              time_marker_line_selected="${base0E}ff"
              keyframe="${base0E}"
              draw_action="#50c8ff"
              preview_back="${base01}"
              metadatabg="${base01}"
              metadatatext="${base05}"
              preview_range="#a14d0066"
              row_alternate="#7f849c23"
              >
              <space>
                <ThemeSpaceGeneric
                  back="${base00}"
                  title="${base05}"
                  text="${base05}"
                  text_hi="${base05}"
                  header="${base00}ff"
                  header_text="${base05}"
                  header_text_hi="${base05}"
                  button="${base00}ff"
                  button_title="${base05}"
                  button_text="${base05}"
                  button_text_hi="${base05}"
                  navigation_bar="${base00}ff"
                  execution_buts="${base00}ff"
                  tab_active="${base04}"
                  tab_inactive="${base00}"
                  tab_back="${base00}ff"
                  tab_outline="${base00}"
                  >
                  <panelcolors>
                    <ThemePanelColors
                      header="${base01}ff"
                      back="${base01}ff"
                      sub_back="${base01}ff"
                      >
                    </ThemePanelColors>
                  </panelcolors>
                </ThemeSpaceGeneric>
              </space>
              <space_list>
                <ThemeSpaceListGeneric
                  list="${base00}"
                  list_title="${base05}"
                  list_text="${base05}"
                  list_text_hi="${base0E}"
                  >
                </ThemeSpaceListGeneric>
              </space_list>
            </ThemeSequenceEditor>
          </sequence_editor>
          <properties>
            <ThemeProperties
              match="${base0E}"
              active_modifier="${base0E}ff"
              >
              <space>
                <ThemeSpaceGeneric
                  back="${base00}"
                  title="${base05}"
                  text="${base05}"
                  text_hi="${base05}"
                  header="${base00}ff"
                  header_text="${base05}"
                  header_text_hi="${base05}"
                  button="${base00}ff"
                  button_title="${base05}"
                  button_text="${base05}"
                  button_text_hi="${base05}"
                  navigation_bar="${base00}ff"
                  execution_buts="${base00}ff"
                  tab_active="${base04}"
                  tab_inactive="${base00}"
                  tab_back="${base00}ff"
                  tab_outline="${base00}"
                  >
                  <panelcolors>
                    <ThemePanelColors
                      header="${base01}ff"
                      back="${base01}ff"
                      sub_back="${base01}ff"
                      >
                    </ThemePanelColors>
                  </panelcolors>
                </ThemeSpaceGeneric>
              </space>
            </ThemeProperties>
          </properties>
          <text_editor>
            <ThemeTextEditor
              line_numbers="${base05}"
              line_numbers_background="${base00}"
              selected_text="#2d4366"
              cursor="#ff0000"
              syntax_builtin="${base08}"
              syntax_symbols="${base0F}"
              syntax_special="${base0B}"
              syntax_preprocessor="${base0E}"
              syntax_reserved="${base09}"
              syntax_comment="#7f849c"
              syntax_string="${base0A}"
              syntax_numbers="${base07}"
              >
              <space>
                <ThemeSpaceGeneric
                  back="${base00}"
                  title="${base05}"
                  text="${base05}"
                  text_hi="${base05}"
                  header="${base00}ff"
                  header_text="${base05}"
                  header_text_hi="${base05}"
                  button="${base00}ff"
                  button_title="${base05}"
                  button_text="${base05}"
                  button_text_hi="${base05}"
                  navigation_bar="${base00}ff"
                  execution_buts="${base00}ff"
                  tab_active="${base04}"
                  tab_inactive="${base00}"
                  tab_back="${base00}ff"
                  tab_outline="${base00}"
                  >
                  <panelcolors>
                    <ThemePanelColors
                      header="${base01}ff"
                      back="${base01}ff"
                      sub_back="${base01}ff"
                      >
                    </ThemePanelColors>
                  </panelcolors>
                </ThemeSpaceGeneric>
              </space>
            </ThemeTextEditor>
          </text_editor>
          <node_editor>
            <ThemeNodeEditor
              grid="#7f849c"
              node_selected="#65527b"
              node_active="${base0E}"
              wire="${base05}ff"
              wire_inner="#8d8d8d"
              wire_select="${base0E}80"
              selected_text="${base05}"
              node_backdrop="${base01}ff"
              converter_node="${base07}"
              color_node="${base0A}"
              group_node="${base0B}"
              group_socket_node="${base05}"
              frame_node="${base04}56"
              matte_node="${base08}"
              distor_node="#74c7ec"
              noodle_curving="5"
              grid_levels="1"
              dash_alpha="0.5"
              input_node="${base08}"
              output_node="${base08}"
              filter_node="${base0E}"
              vector_node="#89b4fa"
              texture_node="${base09}"
              shader_node="${base0B}"
              script_node="#74c7ec"
              pattern_node="#6c696f"
              layout_node="#6c696f"
              geometry_node="${base0B}"
              attribute_node="#89b4fa"
              simulation_zone="${base0E}33"
              >
              <space>
                <ThemeSpaceGeneric
                  back="${base00}"
                  title="${base05}"
                  text="${base05}"
                  text_hi="${base05}"
                  header="${base00}ff"
                  header_text="${base05}"
                  header_text_hi="${base05}"
                  button="${base00}00"
                  button_title="${base05}"
                  button_text="${base05}"
                  button_text_hi="${base05}"
                  navigation_bar="${base00}ff"
                  execution_buts="${base00}ff"
                  tab_active="${base04}"
                  tab_inactive="${base00}"
                  tab_back="${base00}ff"
                  tab_outline="${base00}"
                  >
                  <panelcolors>
                    <ThemePanelColors
                      header="${base01}ff"
                      back="${base01}ff"
                      sub_back="${base01}ff"
                      >
                    </ThemePanelColors>
                  </panelcolors>
                </ThemeSpaceGeneric>
              </space>
              <space_list>
                <ThemeSpaceListGeneric
                  list="${base00}"
                  list_title="${base05}"
                  list_text="${base05}"
                  list_text_hi="${base0E}"
                  >
                </ThemeSpaceListGeneric>
              </space_list>
            </ThemeNodeEditor>
          </node_editor>
          <outliner>
            <ThemeOutliner
              match="${base0B}"
              selected_highlight="${base00}"
              active="${base0E}"
              selected_object="${base05}"
              active_object="${base00}"
              edited_object="${base0B}66"
              row_alternate="${base05}04"
              >
              <space>
                <ThemeSpaceGeneric
                  back="${base00}"
                  title="${base05}"
                  text="${base05}"
                  text_hi="${base05}"
                  header="${base00}ff"
                  header_text="${base05}"
                  header_text_hi="${base05}"
                  button="${base00}ff"
                  button_title="${base05}"
                  button_text="${base05}"
                  button_text_hi="${base05}"
                  navigation_bar="${base00}ff"
                  execution_buts="${base00}ff"
                  tab_active="${base04}"
                  tab_inactive="${base00}"
                  tab_back="${base00}ff"
                  tab_outline="${base00}"
                  >
                  <panelcolors>
                    <ThemePanelColors
                      header="${base01}ff"
                      back="${base01}ff"
                      sub_back="${base01}ff"
                      >
                    </ThemePanelColors>
                  </panelcolors>
                </ThemeSpaceGeneric>
              </space>
            </ThemeOutliner>
          </outliner>
          <info>
            <ThemeInfo
              info_selected="${base07}"
              info_selected_text="${base00}"
              info_error="${base08}ff"
              info_error_text="${base00}"
              info_warning="${base0A}ff"
              info_warning_text="${base00}"
              info_info="#89b4faff"
              info_info_text="${base00}"
              info_debug="${base0E}ff"
              info_debug_text="${base00}"
              info_property="${base0B}ff"
              info_property_text="${base00}"
              info_operator="${base0C}ff"
              info_operator_text="${base00}"
              >
              <space>
                <ThemeSpaceGeneric
                  back="${base00}"
                  title="${base05}"
                  text="${base05}"
                  text_hi="${base05}"
                  header="${base00}ff"
                  header_text="${base05}"
                  header_text_hi="${base05}"
                  button="${base00}ff"
                  button_title="${base05}"
                  button_text="${base05}"
                  button_text_hi="${base05}"
                  navigation_bar="${base00}ff"
                  execution_buts="${base00}ff"
                  tab_active="${base04}"
                  tab_inactive="${base00}"
                  tab_back="${base00}ff"
                  tab_outline="${base00}"
                  >
                  <panelcolors>
                    <ThemePanelColors
                      header="${base01}ff"
                      back="${base01}ff"
                      sub_back="${base01}ff"
                      >
                    </ThemePanelColors>
                  </panelcolors>
                </ThemeSpaceGeneric>
              </space>
            </ThemeInfo>
          </info>
          <preferences>
            <ThemePreferences>
              <space>
                <ThemeSpaceGeneric
                  back="${base00}"
                  title="${base05}"
                  text="${base05}"
                  text_hi="${base05}"
                  header="${base00}ff"
                  header_text="${base05}"
                  header_text_hi="${base05}"
                  button="${base00}ff"
                  button_title="${base05}"
                  button_text="${base05}"
                  button_text_hi="${base05}"
                  navigation_bar="${base00}ff"
                  execution_buts="${base00}ff"
                  tab_active="${base04}"
                  tab_inactive="${base00}"
                  tab_back="${base00}ff"
                  tab_outline="${base00}"
                  >
                  <panelcolors>
                    <ThemePanelColors
                      header="${base01}ff"
                      back="${base01}ff"
                      sub_back="${base01}ff"
                      >
                    </ThemePanelColors>
                  </panelcolors>
                </ThemeSpaceGeneric>
              </space>
            </ThemePreferences>
          </preferences>
          <console>
            <ThemeConsole
              line_output="${base07}"
              line_input="${base05}"
              line_info="${base0B}"
              line_error="${base08}"
              cursor="${base0E}"
              select="${base00}ff"
              >
              <space>
                <ThemeSpaceGeneric
                  back="${base00}"
                  title="${base05}"
                  text="${base05}"
                  text_hi="${base05}"
                  header="${base00}ff"
                  header_text="${base05}"
                  header_text_hi="${base05}"
                  button="${base00}ff"
                  button_title="${base05}"
                  button_text="${base05}"
                  button_text_hi="${base05}"
                  navigation_bar="${base00}ff"
                  execution_buts="${base00}ff"
                  tab_active="${base04}"
                  tab_inactive="${base00}"
                  tab_back="${base00}ff"
                  tab_outline="${base00}"
                  >
                  <panelcolors>
                    <ThemePanelColors
                      header="${base01}ff"
                      back="${base01}ff"
                      sub_back="${base01}ff"
                      >
                    </ThemePanelColors>
                  </panelcolors>
                </ThemeSpaceGeneric>
              </space>
            </ThemeConsole>
          </console>
          <clip_editor>
            <ThemeClipEditor
              grid="${base05}ff"
              marker_outline="${base01}"
              marker="#808000"
              active_marker="${base05}"
              selected_marker="#ffff00"
              disabled_marker="#7f0000"
              locked_marker="#7f7f7f"
              path_before="#ff0000"
              path_after="#0000ff"
              path_keyframe_before="#ffc4c4"
              path_keyframe_after="#c4c4ff"
              frame_current="#4772b3"
              time_scrub_background="${base01}ff"
              time_marker_line="${base05}4d"
              time_marker_line_selected="${base05}b3"
              strips="${base05}"
              strips_selected="${base0E}"
              metadatabg="${base01}"
              metadatatext="${base05}"
              handle_free="${base01}"
              handle_auto="#909000"
              handle_align="#803060"
              handle_sel_free="${base01}"
              handle_sel_auto="#f0ff40"
              handle_sel_align="#f090a0"
              handle_auto_clamped="#994030"
              handle_sel_auto_clamped="#f0af90"
              handle_vertex="${base01}"
              handle_vertex_select="${base0E}"
              handle_vertex_size="5"
              >
              <space>
                <ThemeSpaceGeneric
                  back="${base00}"
                  title="${base05}"
                  text="${base05}"
                  text_hi="${base05}"
                  header="${base00}ff"
                  header_text="${base05}"
                  header_text_hi="${base05}"
                  button="#8185bb00"
                  button_title="${base05}"
                  button_text="${base05}"
                  button_text_hi="${base05}"
                  navigation_bar="${base00}ff"
                  execution_buts="${base00}ff"
                  tab_active="${base04}"
                  tab_inactive="${base00}"
                  tab_back="${base00}ff"
                  tab_outline="${base00}"
                  >
                  <panelcolors>
                    <ThemePanelColors
                      header="${base01}ff"
                      back="${base01}ff"
                      sub_back="${base01}ff"
                      >
                    </ThemePanelColors>
                  </panelcolors>
                </ThemeSpaceGeneric>
              </space>
              <space_list>
                <ThemeSpaceListGeneric
                  list="${base00}"
                  list_title="${base05}"
                  list_text="${base05}"
                  list_text_hi="${base0E}"
                  >
                </ThemeSpaceListGeneric>
              </space_list>
            </ThemeClipEditor>
          </clip_editor>
          <topbar>
            <ThemeTopBar>
              <space>
                <ThemeSpaceGeneric
                  back="${base00}"
                  title="${base05}"
                  text="${base05}"
                  text_hi="${base05}"
                  header="${base00}ff"
                  header_text="${base05}"
                  header_text_hi="${base05}"
                  button="${base00}ff"
                  button_title="${base05}"
                  button_text="${base05}"
                  button_text_hi="${base05}"
                  navigation_bar="${base00}ff"
                  execution_buts="${base00}ff"
                  tab_active="${base04}"
                  tab_inactive="${base00}"
                  tab_back="${base00}ff"
                  tab_outline="${base00}"
                  >
                  <panelcolors>
                    <ThemePanelColors
                      header="${base00}ff"
                      back="${base00}ff"
                      sub_back="${base00}ff"
                      >
                    </ThemePanelColors>
                  </panelcolors>
                </ThemeSpaceGeneric>
              </space>
            </ThemeTopBar>
          </topbar>
          <statusbar>
            <ThemeStatusBar>
              <space>
                <ThemeSpaceGeneric
                  back="${base00}"
                  title="${base05}"
                  text="${base05}"
                  text_hi="${base05}"
                  header="${base00}ff"
                  header_text="${base05}"
                  header_text_hi="${base05}"
                  button="${base00}ff"
                  button_title="${base05}"
                  button_text="${base05}"
                  button_text_hi="${base05}"
                  navigation_bar="${base00}ff"
                  execution_buts="${base00}ff"
                  tab_active="${base04}"
                  tab_inactive="${base00}"
                  tab_back="${base00}ff"
                  tab_outline="${base00}"
                  >
                  <panelcolors>
                    <ThemePanelColors
                      header="${base00}ff"
                      back="${base00}ff"
                      sub_back="${base00}ff"
                      >
                    </ThemePanelColors>
                  </panelcolors>
                </ThemeSpaceGeneric>
              </space>
            </ThemeStatusBar>
          </statusbar>
          <spreadsheet>
            <ThemeSpreadsheet
              row_alternate="${base01}ff"
              >
              <space>
                <ThemeSpaceGeneric
                  back="${base00}"
                  title="${base05}"
                  text="${base05}"
                  text_hi="${base05}"
                  header="${base00}ff"
                  header_text="${base05}"
                  header_text_hi="${base05}"
                  button="${base00}ff"
                  button_title="${base05}"
                  button_text="${base05}"
                  button_text_hi="${base05}"
                  navigation_bar="${base00}ff"
                  execution_buts="${base00}ff"
                  tab_active="${base04}"
                  tab_inactive="${base00}"
                  tab_back="${base00}ff"
                  tab_outline="${base00}"
                  >
                  <panelcolors>
                    <ThemePanelColors
                      header="${base01}ff"
                      back="${base01}ff"
                      sub_back="${base01}ff"
                      >
                    </ThemePanelColors>
                  </panelcolors>
                </ThemeSpaceGeneric>
              </space>
              <space_list>
                <ThemeSpaceListGeneric
                  list="${base00}"
                  list_title="${base05}"
                  list_text="${base05}"
                  list_text_hi="${base0E}"
                  >
                </ThemeSpaceListGeneric>
              </space_list>
            </ThemeSpreadsheet>
          </spreadsheet>
          <bone_color_sets>
            <ThemeBoneColorSet
              normal="#9a0000"
              select="#bd1111"
              active="#f70a0a"
              show_colored_constraints="FALSE"
              >
            </ThemeBoneColorSet>
            <ThemeBoneColorSet
              normal="#f74018"
              select="#f66913"
              active="#fa9900"
              show_colored_constraints="FALSE"
              >
            </ThemeBoneColorSet>
            <ThemeBoneColorSet
              normal="#1e9109"
              select="#59b70b"
              active="#83ef1d"
              show_colored_constraints="FALSE"
              >
            </ThemeBoneColorSet>
            <ThemeBoneColorSet
              normal="#0a3694"
              select="#3667df"
              active="#5ec1ef"
              show_colored_constraints="FALSE"
              >
            </ThemeBoneColorSet>
            <ThemeBoneColorSet
              normal="#a9294e"
              select="#c1416a"
              active="#f05d91"
              show_colored_constraints="FALSE"
              >
            </ThemeBoneColorSet>
            <ThemeBoneColorSet
              normal="#430c78"
              select="#543aa3"
              active="#8764d5"
              show_colored_constraints="FALSE"
              >
            </ThemeBoneColorSet>
            <ThemeBoneColorSet
              normal="#24785a"
              select="#3c9579"
              active="#6fb6ab"
              show_colored_constraints="FALSE"
              >
            </ThemeBoneColorSet>
            <ThemeBoneColorSet
              normal="#4b707c"
              select="#6a8691"
              active="#9bc2cd"
              show_colored_constraints="FALSE"
              >
            </ThemeBoneColorSet>
            <ThemeBoneColorSet
              normal="#f4c90c"
              select="#eec236"
              active="#f3ff00"
              show_colored_constraints="FALSE"
              >
            </ThemeBoneColorSet>
            <ThemeBoneColorSet
              normal="#1e2024"
              select="#484c56"
              active="${base05}"
              show_colored_constraints="FALSE"
              >
            </ThemeBoneColorSet>
            <ThemeBoneColorSet
              normal="#6f2f6a"
              select="#9845be"
              active="#d330d6"
              show_colored_constraints="FALSE"
              >
            </ThemeBoneColorSet>
            <ThemeBoneColorSet
              normal="#6c8e22"
              select="#7fb022"
              active="#bbef5b"
              show_colored_constraints="FALSE"
              >
            </ThemeBoneColorSet>
            <ThemeBoneColorSet
              normal="#8d8d8d"
              select="#b0b0b0"
              active="#dedede"
              show_colored_constraints="FALSE"
              >
            </ThemeBoneColorSet>
            <ThemeBoneColorSet
              normal="#834326"
              select="#8b5811"
              active="#bd6a11"
              show_colored_constraints="FALSE"
              >
            </ThemeBoneColorSet>
            <ThemeBoneColorSet
              normal="#08310e"
              select="#1c430b"
              active="#34622b"
              show_colored_constraints="FALSE"
              >
            </ThemeBoneColorSet>
            <ThemeBoneColorSet
              normal="${base01}"
              select="${base01}"
              active="${base01}"
              show_colored_constraints="FALSE"
              >
            </ThemeBoneColorSet>
            <ThemeBoneColorSet
              normal="${base01}"
              select="${base01}"
              active="${base01}"
              show_colored_constraints="FALSE"
              >
            </ThemeBoneColorSet>
            <ThemeBoneColorSet
              normal="${base01}"
              select="${base01}"
              active="${base01}"
              show_colored_constraints="FALSE"
              >
            </ThemeBoneColorSet>
            <ThemeBoneColorSet
              normal="${base01}"
              select="${base01}"
              active="${base01}"
              show_colored_constraints="FALSE"
              >
            </ThemeBoneColorSet>
            <ThemeBoneColorSet
              normal="${base01}"
              select="${base01}"
              active="${base01}"
              show_colored_constraints="FALSE"
              >
            </ThemeBoneColorSet>
          </bone_color_sets>
          <collection_color>
            <ThemeCollectionColor
              color="${base08}"
              >
            </ThemeCollectionColor>
            <ThemeCollectionColor
              color="${base09}"
              >
            </ThemeCollectionColor>
            <ThemeCollectionColor
              color="${base0A}"
              >
            </ThemeCollectionColor>
            <ThemeCollectionColor
              color="${base0B}"
              >
            </ThemeCollectionColor>
            <ThemeCollectionColor
              color="${base0C}"
              >
            </ThemeCollectionColor>
            <ThemeCollectionColor
              color="${base0E}"
              >
            </ThemeCollectionColor>
            <ThemeCollectionColor
              color="#f5c2e7"
              >
            </ThemeCollectionColor>
            <ThemeCollectionColor
              color="${base06}"
              >
            </ThemeCollectionColor>
          </collection_color>
          <strip_color>
            <ThemeStripColor
              color="${base08}"
              >
            </ThemeStripColor>
            <ThemeStripColor
              color="${base09}"
              >
            </ThemeStripColor>
            <ThemeStripColor
              color="${base0A}"
              >
            </ThemeStripColor>
            <ThemeStripColor
              color="${base0B}"
              >
            </ThemeStripColor>
            <ThemeStripColor
              color="${base0C}"
              >
            </ThemeStripColor>
            <ThemeStripColor
              color="${base0E}"
              >
            </ThemeStripColor>
            <ThemeStripColor
              color="${base07}"
              >
            </ThemeStripColor>
            <ThemeStripColor
              color="${base06}"
              >
            </ThemeStripColor>
            <ThemeStripColor
              color="${base04}"
              >
            </ThemeStripColor>
          </strip_color>
        </Theme>
        <ThemeStyle>
          <panel_title>
            <ThemeFontStyle
              points="11"
              shadow="3"
              shadow_offset_x="0"
              shadow_offset_y="-1"
              shadow_alpha="0.5"
              shadow_value="0"
              >
            </ThemeFontStyle>
          </panel_title>
          <widget_label>
            <ThemeFontStyle
              points="11"
              shadow="3"
              shadow_offset_x="0"
              shadow_offset_y="-1"
              shadow_alpha="0.5"
              shadow_value="0"
              >
            </ThemeFontStyle>
          </widget_label>
          <widget>
            <ThemeFontStyle
              points="11"
              shadow="1"
              shadow_offset_x="0"
              shadow_offset_y="-1"
              shadow_alpha="0.5"
              shadow_value="0"
              >
            </ThemeFontStyle>
          </widget>
        </ThemeStyle>
      </bpy>
    '';
  };
}
