grafana:
    smtp:
        user: ENC[AES256_GCM,data:2Aot7n9evMdtLHk0KMalaWi1S+g15w==,iv:Dk1YWI+hU//taPStWEl4h9/xvvA21BdyrjQAUkzoPAU=,tag:jECpkri4iRP934L5R/yv5g==,type:str]
        host: ENC[AES256_GCM,data:1g5m1Q8nvP1BH6M7j8jazpHzUIdT9PKLMg==,iv:vElD7deDW156rdv+T/lpPYaQDUd+uNztNwYs+IPjJi8=,tag:dXnGQYDlwWS3lYiifTcxEw==,type:str]
        password: ENC[AES256_GCM,data:AH4V5EqAuk8nb65vWM4=,iv:6ypWTaaMtSFIUN7ICLiwtHHoRxP6p1UOMbxGr5lfSXE=,tag:/FzB7xRzNoNKFrP8Izay9Q==,type:str]
    hint: ENC[AES256_GCM,data:X2xRxKtGAD9rGFSd+oXTc+OQZmLC3YOK,iv:VWxxLvRuEhYuj3CtNEdxpfZkP9Dyx0rG6CLxbZfoMaw=,tag:XQYL0UknIPQzgFi9ZrZnHA==,type:str]
sops:
    age:
        - recipient: age1hqmjhpm7a9w2cnjdvnutk65uqkjpd4huyvd5udqs5yxlzuthyupspxq2ft
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtK2hUSzdnTnREUGFuOGo3
            M1RLSVN3dzdINnNONEs4N1JHY2hHd2VHcVJVCmlUNzJrVFBSdU1pNWNuVVFkemhn
            bFVub01MaURERnROWEV5NzA3ejVNQTQKLS0tIE9ydWJhaWhmaVRoeHI1SHQxZVo5
            NDc5SW81Y3BGZ3J4Zk1RS3BQbkpFODQKC/Z8b4Va/+wv+6Bh1xFcV4xREu4uWyeX
            InlZ6b4A7T6/AXd9UQseyPqQ/RnTL3gxDZaOB6jTIvJyrOAocFs+1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-08T22:25:52Z"
    mac: ENC[AES256_GCM,data:D9tph0VC0AMRMrjtrgNCgcFxKCuBDDyvorPlSXjycTILb0ArBcrE/PKN3VZ1AZOfEgFMofQSa91jOq8e5ufno/ojGfmFeXauuzu5p6LNr4WuALTssZuXQwT1k8ghVBFe/WkQx4yCEigIhbjzOtmJtvWyrMTr+NFAh8MZYOsMFns=,iv:4AMF/0qKIzYVWgcdMm5ZuWtRXMVv0qOct9Pw2QyGI1k=,tag:3SJPH0c1f3pzyBUCIxCpKw==,type:str]
    pgp:
        - created_at: "2025-09-08T23:37:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DW7pTteVLMFESAQdARWILeKXwgsKVzmuer3yKaymU5VcSy+IP4dKEJKlCh24w
            kBUnXsQhagnMmJ4/Rz4RpI8mXO1xy29G3IybFw4aMRl/ycdaZs48oV8YdlY2vRci
            0lwBp8uSnNt8e+VT3rQSWmLxbizGEtVISdUfkp4KM1fpb5CctdehSICFMQ/edS+4
            JBbBbrL9VJMz5T7FXaIgK8IIu1nYwkfrdVnsdnTQyZJPDcdRi3H+5JCbYkLz5g==
            =OMIN
            -----END PGP MESSAGE-----
          fp: CFDDC2FC81DEE54D1C4BFF58538305FABF463DE5
    unencrypted_suffix: _unencrypted
    version: 3.10.2
