grafana:
    smtp:
        user: ENC[AES256_GCM,data:2Aot7n9evMdtLHk0KMalaWi1S+g15w==,iv:Dk1YWI+hU//taPStWEl4h9/xvvA21BdyrjQAUkzoPAU=,tag:jECpkri4iRP934L5R/yv5g==,type:str]
        host: ENC[AES256_GCM,data:1g5m1Q8nvP1BH6M7j8jazpHzUIdT9PKLMg==,iv:vElD7deDW156rdv+T/lpPYaQDUd+uNztNwYs+IPjJi8=,tag:dXnGQYDlwWS3lYiifTcxEw==,type:str]
        password: ENC[AES256_GCM,data:AH4V5EqAuk8nb65vWM4=,iv:6ypWTaaMtSFIUN7ICLiwtHHoRxP6p1UOMbxGr5lfSXE=,tag:/FzB7xRzNoNKFrP8Izay9Q==,type:str]
    hint: ENC[AES256_GCM,data:X2xRxKtGAD9rGFSd+oXTc+OQZmLC3YOK,iv:VWxxLvRuEhYuj3CtNEdxpfZkP9Dyx0rG6CLxbZfoMaw=,tag:XQYL0UknIPQzgFi9ZrZnHA==,type:str]
sops:
    age:
        - recipient: age1m7p4yrmzp2w4hcwpsc8hg6vxaprrq5mffjs9mv7vxdjqd7628d0qt5ln3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdDR3NjlZQnYzYnZvbmhr
            WmFzY3N5eU9FQzMwVExIVitQdDFya3JlaXdrCnYyejBZTU5OeEJRL2Vyci95Qy9Y
            ZTRXdU1nT3dtYjhZUVhJdytTTEgvK1EKLS0tIHdOdGhId1k2UkkwcGhHTmNJVmwx
            OCtQdWNPQ3h5MStzbjl4Wnp5N1lFaWMKT8QFwqwUGL1NpGXUDuodIKNVd9lhNRsN
            Y93Vk+DFaioW5sygJDTieP1nDHFO4mJdI4wfcfV/kNZDQus2URommA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-08T22:25:52Z"
    mac: ENC[AES256_GCM,data:D9tph0VC0AMRMrjtrgNCgcFxKCuBDDyvorPlSXjycTILb0ArBcrE/PKN3VZ1AZOfEgFMofQSa91jOq8e5ufno/ojGfmFeXauuzu5p6LNr4WuALTssZuXQwT1k8ghVBFe/WkQx4yCEigIhbjzOtmJtvWyrMTr+NFAh8MZYOsMFns=,iv:4AMF/0qKIzYVWgcdMm5ZuWtRXMVv0qOct9Pw2QyGI1k=,tag:3SJPH0c1f3pzyBUCIxCpKw==,type:str]
    pgp:
        - created_at: "2025-09-08T22:17:24Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DW7pTteVLMFESAQdAXeB+6TxfeQemKVXVRgO/sNWgYOF42wdAwj3mA7UjCCcw
            WEM7CDSJVE1+49AUbX9aQpyHssv8ShCb6mSOTIx4bBWZwyT9heVE+A2X5TdFdMcT
            0lwBavN1IfXemOpqwIEJneQU9H6p2IC5gSQaY/IP57xXJi7oRF+7wiMrySi1trqg
            KtL7Lx0aOdaHpN9Cie2Y8HBk78BIhJfui8/68DGVbw4di61+SZ3VzvknhfDUDA==
            =vjU2
            -----END PGP MESSAGE-----
          fp: CFDDC2FC81DEE54D1C4BFF58538305FABF463DE5
    unencrypted_suffix: _unencrypted
    version: 3.10.2
